version: '2'

services:
  web-container:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - APP_CONFIG='{"articleUrl":"content/article.md"}'
